- name: Deploy Splunk
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    COMMON_APP_DIR: "/edx/app"
    common_web_group: "www-data"
    ENABLE_DATADOG: True
    ENABLE_SPLUNKFORWARDER: True
    ENABLE_NEWRELIC: True 
  roles:
    - aws
    - splunk-server
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC

